# In the following requests the variable baseUrl is used.
# Its value is set here.
@baseUrl = http://localhost:4004



POST {{baseUrl}}/odata/v4/sales-order/createSalesOrder

Content-Type: application/json

{
  	

}

